image: 
  - ubuntu
  - Ubuntu

install:
  - sh: uname -a
  - sh: lsb_release -a
  - sh: sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
  - sh: sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
  - sh: sudo apt-add-repository ppa:dartsim/ppa
  - sh: sudo apt-add-repository ppa:personalrobotics/ppa
  - sh: sudo apt-get update
  - sh: sudo apt-get --yes install cmake build-essential libboost-filesystem-dev libdart6-optimizer-nlopt-dev libdart6-utils-dev libdart6-utils-urdf-dev libmicrohttpd-dev libompl-dev libtinyxml2-dev libyaml-cpp-dev
  #- sh: sudo apt-get --yes install pr-control-msgs
  - sh: sudo apt-get --yes install ros-lunar-actionlib ros-lunar-geometry-msgs ros-lunar-interactive-markers ros-lunar-roscpp ros-lunar-std-msgs ros-lunar-tf ros-lunar-trajectory-msgs ros-lunar-visualization-msgs
  - sh: cmake --version
  - sh: gcc --version
  - sh: source /opt/ros/lunar/setup.bash

#script:
#  - cmd: cmake --version
#  - cmd: gcc --version

build: off
