image: ubuntu

install:
  - lsb_release -a
  - sudo apt-add-repository ppa:dartsim/ppa
  - sudo apt-get update
  - sudo apt-get --yes install cmake
  - cmake --version
  #- gcc --version
  #- clang --version

#script:
#  - cmd: cmake --version
#  - cmd: gcc --version

build: off
