image: ubuntu

install:
  - ls -al
  - sudo apt-add-repository ppa:dartsim/ppa
  - sudo apt-get update
  - cmake --version
  - gcc --version
  - clang --version
  - lsb_release -a

#script:
#  - cmd: cmake --version
#  - cmd: gcc --version

build: off
